# Generated by Django 4.2.8 on 2024-07-02 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('chatid', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ChatModel',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'UserModel',
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('messageid', models.AutoField(primary_key=True, serialize=False)),
                ('messagetype', models.BooleanField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(db_column='chatid', on_delete=django.db.models.deletion.CASCADE, to='api.chatmodel')),
            ],
            options={
                'db_table': 'MessageModel',
            },
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='user',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='api.usermodel'),
        ),
    ]
