# Generated by Django 4.2.8 on 2024-07-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
