# Generated by Django 5.1.3 on 2025-03-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chathistory_chat_id_alter_title_title_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='title_id',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
