# Generated by Django 4.2.8 on 2025-03-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_title_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
