# Generated by Django 4.2.8 on 2025-03-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_title_user_id_delete_chathistory_delete_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('title_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('gpt_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(db_column='username', default='', on_delete=django.db.models.deletion.CASCADE, to='api.usermodel')),
            ],
            options={
                'db_table': 'Title',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('gpt_message', models.TextField()),
                ('vote', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gpt_id', models.ForeignKey(blank=True, db_column='gpt_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='api.title')),
                ('title_id', models.ForeignKey(blank=True, db_column='title_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_titles', to='api.title')),
            ],
            options={
                'db_table': 'ChatHistory',
            },
        ),
    ]
