# Generated by Django 4.2.8 on 2025-03-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_title_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTs',
            fields=[
                ('gpt_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('gpt', models.TextField()),
            ],
            options={
                'db_table': 'GPTs',
            },
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='gpt_id',
            field=models.ForeignKey(blank=True, db_column='gpt_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_gpt_ids', to='api.gpts'),
        ),
        migrations.AlterField(
            model_name='title',
            name='gpt_id',
            field=models.ForeignKey(blank=True, db_column='gpt_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_gpt_ids', to='api.gpts'),
        ),
    ]
