# -*- coding: utf-8 -*-
"""p1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0qrBW6zloWZDaVZYDwcfabLfEheT29O
"""

from peft import PeftModel, PeftConfig
from transformers import AutoModelForCausalLM,AutoTokenizer

model_name = "TheBloke/Mistral-7B-Instruct-v0.2-GPTQ"
model = AutoModelForCausalLM.from_pretrained(model_name,
                                             device_map="auto",
                                             trust_remote_code=False,
                                             revision="main")
config = PeftConfig.from_pretrained("Dantewada/LegalGPT-ft")
model = PeftModel.from_pretrained(model, "Dantewada/LegalGPT-ft")

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

model.save_pretrained("/content/drive/MyDrive/LegalGPT-ft-Model") #path to save Model
tokenizer.save_pretrained("/content/drive/MyDrive/LegalGPT-ft-Tokenizer") #path to save Tokenizer